### ISSUE TITLE
Запрос на добавление ссылки в коллекцию крутых штук

### ISSUE THREAD

**Issue by felixexter** [CSSSR/sputnik#28]
[Посмотреть можно здесь](https://github.com/CSSSR/sputnik/blob/master/Awesome%20Features.md).

Добавляем заголовок и ссылку в таком формате:

```
Вдохновляющие эффекты для полей ввода
http://tympanus.net/Development/TextInputEffects/
```

**Comment by Nitive** [comment]
Надо закрыть
