### ISSUE TITLE
Добавить описание тестирования граничных случаев (corner cases)

### ISSUE THREAD

**Issue by daynin** [CSSSR/sputnik#51]
Например, [тут](https://github.com/CSSSR/sputnik/blob/master/docs/JavaScript/Testing.md) сказано:

```
Например, для функции сложения это будут варианты:
- сложение с нулем;
- сложение отрицательных чисел;
- сложение дробных чисел.
Например, нет смысла проверять несколько похожих вариантов: 2 и 4, 3 и 3.
Какие варианты стоит проверять зависит уже от самой функции.
```
Но не сказано какие именно варианты нужно тестировать. А именно, для любого кода целесообразно протестировать как минимум следующие кейсы:

- Ожидаемое корректное поведение
- Ожидаемое некорректное поведение

Плюс следует отметить, что если вы не видели, как тест падает, то такому тесту доверять нельзя, так как легко пойти по positive way и пропустить ошибку в коде

**Comment by dzhiriki** [comment]
Про то, что нужно проверять, что тест не проходит написано в секции про TDD. Но да, стоит на это больше внимания акцентировать.

А что ты тут подразумеваешь под ожидаемым некорректным поведением? Если поведение ожидаемо, то оно заведомо корректное. Или я как-то не так тебя понял?

**Comment by daynin** [comment]
@dzhiriki да, возможно, я не совсем точно выразился
> А что ты тут подразумеваешь под ожидаемым некорректным поведением?

Я имел в виду, что нужно тестировать не только positive way. Например, для `sum` это будет проверка 

```javascript
it('should not return 42 if we pass 10 and 20', () => {
  expect(sum(10, 20)).not.toBe(42)
})
```

То есть мы должны проверить не только кейсы, которые мы как разработчики и так предполагаем увидеть, но и кейсы, которые заведомо неверны.

**Comment by dzhiriki** [comment]
Понял. Да, стоит подобнее раскрыть этот момент. А то нюансов тут достаточно:
- Если мы тестируем, что 10 и 20 возвращает 30, то нет особого смысла делать тест на не равно 42.
- Более подробно описать в каких случаях с чем сравнивать. Почему мы тут сравниваем с 42, а не 37? 
- В каких случаях вообще делать такую проверку и почему её не стоит заменять на обратную

**Comment by daynin** [comment]
@dzhiriki 

> Если мы тестируем, что 10 и 20 возвращает 30, то нет особого смысла делать тест на не равно 42.

Безусловно, это был только пример. Возможно, не самый удачный, так как использовал для иллюстрации крайне простую функцию `sum(a, b)`, которую на самом деле в большинстве случаев и тестировать не нужно. Но, если тесты пишутся для кода со сложной логикой, то такие кейсы крайне желательны

Есть [отличное видео](https://www.youtube.com/watch?v=vKA4w2O61Xo), объясняющее, почему важно тестировать negative cases. Люди, к сожалению, склонны следовать только positive way и тесты могут быть false positive. Извини, что так много англицизмов, но я, если честно, не знаю, как это правильно и емко описать по-русски, чтобы это не звучало странно :)

**Comment by dzhiriki** [comment]
Пункты, что я описал выше были адресованы не тебе, а просто для истории, чтобы потом не вспоминать \ придумывать, что хотели описать. Так-то я понял о чем речь :)

Оффтоп: Видео я видел.  В «ГП и МРМ» была такая же игра, к слову :)

**Comment by daynin** [comment]
В #65 значительно доработал раздел "Testing", этот issue уже не актуален
