### ISSUE TITLE
Уточнения о процессе Code Review

### ISSUE THREAD

**Issue by acherkashin** [CSSSR/sputnik#79]
Большое спасибо!
Прочитал вашу документацию про [Code Review](http://sputnik.csssr.ru/Git/PullRequests.html#code-review). 

Хотелось бы подробнее узнать о следующих моментах:
- Как выбираются ревьюеры?
- Сколько времени есть у разработчиков на ревью?
- Что делать, если разработчик, который должен сделать ревью занят и никак не находит время на ревью вашего кода. К тому же он является единственным разработчиком который может произвести данное ревью.
- Допустим вас назначают ревьюером для кода, с которым вы никогда не сталкивались и не имеете экспертизы, как проводить ревью в данном случае и нужно ли его проводить именно вам?

**Comment by daynin** [comment]
Отличные вопросы!

> Как выбираются ревьюеры?

Ревьеры не назначаются, любой разработчик из команды может ревьюить PR. Когда набирается 2 апрува, то PR мержится либо последним апрувнувшим, либо автором PR (если последний апрувнувший забыл это сделать).


> Сколько времени есть у разработчиков на ревью?

Столько, сколько потребуется. Мы не задаем никаких лимитов на code review. Но мы при этом еще на стадии планирования стараемся декомпозировать задачи так, чтобы PRs не были очень большими, что в большинстве случаев позволяет проводить ревью относительно быстро. Иногда, конечно, бывают большие, либо сложные PRs, на которые требуется много времени. В любом случае если даже требуется времени больше чем обычно, то мы его тратим, так как это важно для итогового качества кода.

Еще очень спасает автоматизация всего, что можно автоматизировать. Использование линтеров, тестов, проверок самого PR при помощи того же dangerjs позволяет ревьюеру не тратить время на различные мелочи, которые легко проверяются автоматически, при этом сосредоточившись на более важных вещах.


> Что делать, если разработчик, который должен сделать ревью занят и никак не находит время на ревью вашего кода.

Мы придерживаемся следующей практики: разработчики делают ревью между задачами, после дейли митинга, после обеда и т. д., то если после того, как они и так либо переключился с работы над задачей на что-то другое, либо закончил предыдущую задачу. При таком подходе всегда появляется свободный разработчик, который открывает PRs и делает ревью, при этом часть PRs он вмержит, так как его апрув будет вторым, части проставит апрув, а в остальных оставит change requests (пропорции могут быть разными). Таким образом PRs несколько раз в день проходят ревью и не скапливаются. И плюс ко всему, не приходится выдергивать разработчика из текущей задачи.


> К тому же он является единственным разработчиком который может произвести данное ревью.

В нашем флоу такое может быть только если он единственный разработчик в команде. На самом деле ревью могут делать все. Когда джун делает ревью кода, который был написан синьором и по совместительству тимлидом, то это тоже очень полезно. Во-первых, джун может задать вопросы по тем местам, которые ему непонятны (здесь code review будет работать как инструмент распространения знаний о проекте), кроме того этими вопросами он может подсветить и проблемы в коде, так как возможно код можно было написать и проще. Да и никто не отменял банальную невнимательность. Что-то пропустить может кто угодно не зависимо от грейда.


> Допустим вас назначают ревьюером для кода, с которым вы никогда не сталкивались и не имеете экспертизы, как проводить ревью в данном случае и нужно ли его проводить именно вам?

Все равно ревью стоит проводить. Например, чтобы разобраться в том, что это за часть проекта/подпроект/проект, плюс ко всему, не зависимо от проекта проблемы в коде могут быть одинаковыми: проблемы с code complexity, проблемы с неправильно спроектированным или проблемным API/архитектурным решением. Это все можно увидеть без детального понимания специфики решаемых бизнес-задач. Конечно, часть проблем может стать очевидной только после более глубокого погружения, но именно поэтому в первую очередь не стоит создавать изолированные зоны в проекте, в которых разбирается только один разработчик. Если у вас все же сложилась такая ситуация, то вам тем более стоит начинать делать корсс-ревью (все делают ревью всех PRs), плюс стоит начинать давать задачи на разные части проекта раным разработчикам. Это позволит уменьшить bus factor и увеличить общее качество кода.

**Comment by acherkashin** [comment]
Круто, Спасибо за ответы! Всё выглядит очень оптимистично, поэтому я решил задать ещё несколько более сложных вопросов 😄.

1. В каких ситуациях вы не делаете код ревью? 
2. Бывают ли PRs, которые должны быть срочно смержены (возможно какой-то критический баг), проводите ли вы ревью в данных ситуациях?
3. Как часто возникают споры во время код ревью и как они разрешаются?
4. Как часто вы созваниваетесь с создателем PR для совместного ревью? Например, если ревьюеру не удаётся самому понять код.
5. Допустим вы декомпозировали задачу на подзадачи. Разработчик сделал первую подзадачу и создал PR, как ему начать делать вторую подзадачу, если она завязана на первую, когда первая всё ещё находится на Review.
6. Если все разработчики ответственны за все PRs, не возникает ли ситуация, когда какой-то разработчик не занимается ревью, зная, что кто-то из его коллег все равно это сделает?
7. Используете ли вы чеклисты для ревью? Например со списком самых популярных ошибок, которые делают разработчики.

**Comment by daynin** [comment]
1. Таких ситуаций практически не бывает. Но можем не сделать code review, например, если нужно внести правку в документацию к проекту (опечатку поправить, какое-то незначительное изменение внести). То есть практически любые изменения проходят через code review. Важно понимать, что code review - это не только инструмент контроля качества кода, но и инструмент распространения знаний о проекте. Если изменение увидели и апрувнули еще 2 человека в команде, то в большинстве случаев можно сказать, что очень значимая часть команды как минимум в курсе изменений.
2. Да, в данных ситуациях мы все равно проводим ревью. Просто в случае срочности меншеним в чате разработчиков (обычно используем alias всей команды в слаке), чтобы они побыстрее посмотрели этот PR. Но криты в проде случаются не так уж и часто, поэтому такие случаи не нарушают общий флоу.
3. Такое случается нечасто, но в случае, когда команда не может придти к пониманию какой из вариантов лучше, окончательное решение принимает тимлид.
4. Нечасто. Такое бывает в случае с сложными задачами. Чаще такие вопросы решаются в обсуждениях в рамках самого PR.
5. Если одна задача блочит другую, то мы можем сделать форк от ветки первой задачи. Если второй PR уже будет готов до момента мерджа первого PR (чего стоит избегать), то можно направить второй PR в ветку первого. Либо слить их в один, если кажется, что так будет проще продолжать ревью.
6. Не припомню, чтобы такие ситуации возникали. Но если возникнут, то тимлид может с этим поработать, призывая разработчика принимать участие в ревью. Бывает другое. Разработчик может немного устать от ревью, но в этом случае он либо просто чуть меньше участвует в ревью сам, либо говорит об этом и берет небольшую паузу (например, пару дней или день). Такое тоже случается редко, но все же случается, здесь тоже нет никаких проблем в том, чтобы позволить ему немного отдохнуть. В общем, ситуации могут быть разные, но все они разрешимые.
7. Да, иногда используем. Есть вещи, которые автоматизировать либо невозможно, либо сложно, подобные вещи бывает что выносим в чеклисты. Но честно говоря, чеклисты работают не очень хорошо, так как через какое-то время глаз замыливается, поэтому все больше и больше уходим в сторону автоматизаций. Чеклисты лучше подходят для open source проектов, где они могут помочь новым контрибьюторам проверить все ли они сделали перед отправкой PR.

**Comment by acherkashin** [comment]
@daynin Большое спасибо за ответы! Их хватит чтобы создать ещё одну страницу в Wiki 😉.
